<?php

namespace Database\Seeders;

use App\Models\Tire;
use Illuminate\Database\Seeder;

class TireSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tires = [
            // Putničke gume
            [
                'sifra' => 'P001',
                'naziv' => 'Michelin Primacy 4 195/65 R15',
                'dimenzije' => '195/65 R15',
                'sirina' => '195',
                'visina' => '65',
                'precnik' => '15',
                'brend' => 'Michelin',
                'kategorija' => 'Putničke',
                'sezona' => 'Ljetne',
                'veleprodajna_cijena' => 85.00,
                'maloprodajna_cijena' => 110.00,
                'nabavna_cijena' => 70.00,
                'kolicina_na_stanju' => 50,
                'eprel_code' => 'EPREL001',
                'is_active' => true,
            ],
            [
                'sifra' => 'P002',
                'naziv' => 'Continental PremiumContact 6 205/55 R16',
                'dimenzije' => '205/55 R16',
                'sirina' => '205',
                'visina' => '55',
                'precnik' => '16',
                'brend' => 'Continental',
                'kategorija' => 'Putničke',
                'sezona' => 'Ljetne',
                'veleprodajna_cijena' => 95.00,
                'maloprodajna_cijena' => 125.00,
                'nabavna_cijena' => 78.00,
                'kolicina_na_stanju' => 40,
                'eprel_code' => 'EPREL002',
                'is_active' => true,
            ],
            [
                'sifra' => 'P003',
                'naziv' => 'Bridgestone Turanza T005 225/45 R17',
                'dimenzije' => '225/45 R17',
                'sirina' => '225',
                'visina' => '45',
                'precnik' => '17',
                'brend' => 'Bridgestone',
                'kategorija' => 'Putničke',
                'sezona' => 'Ljetne',
                'veleprodajna_cijena' => 105.00,
                'maloprodajna_cijena' => 140.00,
                'nabavna_cijena' => 88.00,
                'kolicina_na_stanju' => 35,
                'eprel_code' => 'EPREL003',
                'is_active' => true,
            ],
            [
                'sifra' => 'P004',
                'naziv' => 'Goodyear UltraGrip 9+ 195/65 R15',
                'dimenzije' => '195/65 R15',
                'sirina' => '195',
                'visina' => '65',
                'precnik' => '15',
                'brend' => 'Goodyear',
                'kategorija' => 'Putničke',
                'sezona' => 'Zimske',
                'veleprodajna_cijena' => 90.00,
                'maloprodajna_cijena' => 120.00,
                'nabavna_cijena' => 75.00,
                'kolicina_na_stanju' => 45,
                'eprel_code' => 'EPREL004',
                'is_active' => true,
            ],

            // SUV gume
            [
                'sifra' => 'S001',
                'naziv' => 'Pirelli Scorpion Verde 235/60 R18',
                'dimenzije' => '235/60 R18',
                'sirina' => '235',
                'visina' => '60',
                'precnik' => '18',
                'brend' => 'Pirelli',
                'kategorija' => 'SUV',
                'sezona' => 'Ljetne',
                'veleprodajna_cijena' => 135.00,
                'maloprodajna_cijena' => 175.00,
                'nabavna_cijena' => 115.00,
                'kolicina_na_stanju' => 30,
                'eprel_code' => 'EPREL005',
                'is_active' => true,
            ],
            [
                'sifra' => 'S002',
                'naziv' => 'Michelin Latitude Sport 3 255/55 R19',
                'dimenzije' => '255/55 R19',
                'sirina' => '255',
                'visina' => '55',
                'precnik' => '19',
                'brend' => 'Michelin',
                'kategorija' => 'SUV',
                'sezona' => 'Ljetne',
                'veleprodajna_cijena' => 155.00,
                'maloprodajna_cijena' => 200.00,
                'nabavna_cijena' => 130.00,
                'kolicina_na_stanju' => 25,
                'eprel_code' => 'EPREL006',
                'is_active' => true,
            ],
            [
                'sifra' => 'S003',
                'naziv' => 'Continental WinterContact TS 850 P SUV 235/65 R17',
                'dimenzije' => '235/65 R17',
                'sirina' => '235',
                'visina' => '65',
                'precnik' => '17',
                'brend' => 'Continental',
                'kategorija' => 'SUV',
                'sezona' => 'Zimske',
                'veleprodajna_cijena' => 145.00,
                'maloprodajna_cijena' => 190.00,
                'nabavna_cijena' => 120.00,
                'kolicina_na_stanju' => 28,
                'eprel_code' => 'EPREL007',
                'is_active' => true,
            ],

            // Kombije gume
            [
                'sifra' => 'K001',
                'naziv' => 'Michelin Agilis 3 215/65 R16C',
                'dimenzije' => '215/65 R16C',
                'sirina' => '215',
                'visina' => '65',
                'precnik' => '16',
                'brend' => 'Michelin',
                'kategorija' => 'Kombije',
                'sezona' => 'Ljetne',
                'veleprodajna_cijena' => 110.00,
                'maloprodajna_cijena' => 145.00,
                'nabavna_cijena' => 92.00,
                'kolicina_na_stanju' => 38,
                'eprel_code' => 'EPREL008',
                'is_active' => true,
            ],
            [
                'sifra' => 'K002',
                'naziv' => 'Continental VanContact 4Season 225/65 R16C',
                'dimenzije' => '225/65 R16C',
                'sirina' => '225',
                'visina' => '65',
                'precnik' => '16',
                'brend' => 'Continental',
                'kategorija' => 'Kombije',
                'sezona' => 'Celogodišnje',
                'veleprodajna_cijena' => 120.00,
                'maloprodajna_cijena' => 160.00,
                'nabavna_cijena' => 100.00,
                'kolicina_na_stanju' => 32,
                'eprel_code' => 'EPREL009',
                'is_active' => true,
            ],
            [
                'sifra' => 'K003',
                'naziv' => 'Goodyear Cargo Vector 2 195/70 R15C',
                'dimenzije' => '195/70 R15C',
                'sirina' => '195',
                'visina' => '70',
                'precnik' => '15',
                'brend' => 'Goodyear',
                'kategorija' => 'Kombije',
                'sezona' => 'Celogodišnje',
                'veleprodajna_cijena' => 100.00,
                'maloprodajna_cijena' => 135.00,
                'nabavna_cijena' => 85.00,
                'kolicina_na_stanju' => 42,
                'eprel_code' => 'EPREL010',
                'is_active' => true,
            ],

            // Teretna gume
            [
                'sifra' => 'T001',
                'naziv' => 'Bridgestone R-Drive 001 215/75 R17.5',
                'dimenzije' => '215/75 R17.5',
                'sirina' => '215',
                'visina' => '75',
                'precnik' => '17.5',
                'brend' => 'Bridgestone',
                'kategorija' => 'Teretna',
                'sezona' => 'Ljetne',
                'veleprodajna_cijena' => 180.00,
                'maloprodajna_cijena' => 240.00,
                'nabavna_cijena' => 155.00,
                'kolicina_na_stanju' => 20,
                'eprel_code' => 'EPREL011',
                'is_active' => true,
            ],
            [
                'sifra' => 'T002',
                'naziv' => 'Michelin X Multi Z 235/75 R17.5',
                'dimenzije' => '235/75 R17.5',
                'sirina' => '235',
                'visina' => '75',
                'precnik' => '17.5',
                'brend' => 'Michelin',
                'kategorija' => 'Teretna',
                'sezona' => 'Ljetne',
                'veleprodajna_cijena' => 195.00,
                'maloprodajna_cijena' => 260.00,
                'nabavna_cijena' => 165.00,
                'kolicina_na_stanju' => 18,
                'eprel_code' => 'EPREL012',
                'is_active' => true,
            ],
        ];

        foreach ($tires as $tire) {
            Tire::create($tire);
        }

        $this->command->info('Kreirano '.count($tires).' primjera guma!');
    }
}
